export type TrophyUserOption = {
  id: number;
  uid: string;
  name: string;
  walletAddress: string | null;
  representedCountry: string | null;
  rating: number | null;
};

export type TrophyRow = {
  id: number;
  trophyId: string;
  displayName: string;
  kind: string;
  family: string;
  tier: string | null;
  status: string;
  currentHolderUserId: number | null;
  currentHolderDisplayName: string | null;
  currentHolderWoloAddress: string | null;
  guardianHolderUserId: number | null;
  guardianHolderDisplayName: string | null;
  guardianHolderWoloAddress: string | null;
  eligibleNationality: string | null;
  eloBandMin: number | null;
  eloBandMax: number | null;
  currentBountyWolo: number;
  projectedBountyWolo: number;
  tributeAmountWolo: number;
  bountyGrowthWolo: number;
  payoutFrequency: string;
  bountyAccrualFrequency: string;
  nftClassId: string | null;
  nftId: string | null;
  nftMetadataUri: string | null;
  nftImageUri: string | null;
  chainStatus: string;
  chainOwnerAddress: string | null;
  lastChainSyncAt: string | null;
  forfeitureNeeded: boolean;
  eligibilityNote: string | null;
  holderSince: string | null;
  appChainMismatch: boolean;
  currentHolderEligible: boolean | null;
  createdAt: string;
  updatedAt: string;
  economics: Array<{
    id: number;
    tributeAmountWolo: number;
    bountyGrowthWolo: number;
    payoutFrequency: string;
    bountyAccrualFrequency: string;
    effectiveFrom: string;
    effectiveTo: string | null;
    changedBy: string | null;
    reason: string | null;
  }>;
};

export type TrophyChallengeRow = {
  id: number;
  trophyId: number;
  trophyKey: string;
  trophyName: string;
  challengeKind: string;
  challengerUserId: number;
  challengerName: string;
  defenderUserId: number | null;
  defenderName: string | null;
  guardianUserId: number | null;
  guardianName: string | null;
  requiredNationality: string | null;
  requiredEloMin: number | null;
  requiredEloMax: number | null;
  eligibilitySnapshot: unknown;
  eligibilityOverride: boolean;
  status: string;
  replayId: number | null;
  replayLabel: string | null;
  scheduledMatchId: number | null;
  watcherSessionId: string | null;
  watcherPairingId: string | null;
  winnerUserId: number | null;
  winnerName: string | null;
  verificationSummary: string | null;
  settlementStatus: string;
  chainTxHash: string | null;
  payoutTxHash: string | null;
  errorState: string | null;
  createdAt: string;
  updatedAt: string;
};

export type TrophyPayoutRow = {
  id: number;
  trophyId: number;
  trophyKey: string;
  trophyName: string;
  recipientUserId: number | null;
  recipientName: string | null;
  recipientWoloAddress: string | null;
  amountWolo: number;
  payoutKind: string;
  status: string;
  scheduledFor: string | null;
  paidAt: string | null;
  txHash: string | null;
  errorState: string | null;
  rawRequest: unknown;
  rawResponse: unknown;
  retryCount: number;
  createdAt: string;
  updatedAt: string;
};

export type TrophyEventRow = {
  id: number;
  trophyId: number;
  trophyKey: string;
  trophyName: string;
  challengeId: number | null;
  eventType: string;
  actorName: string | null;
  actorRole: string;
  initiatedBy: string;
  fromHolderName: string | null;
  toHolderName: string | null;
  fromWoloAddress: string | null;
  toWoloAddress: string | null;
  amountWolo: number | null;
  replayId: number | null;
  chainTxHash: string | null;
  status: string;
  rawRequest: unknown;
  rawResponse: unknown;
  errorMessage: string | null;
  retryCount: number;
  createdAt: string;
};

export type TrophySettingRow = {
  key: string;
  value: unknown;
  reason: string | null;
  changedBy: string | null;
  updatedAt: string;
};

export type TrophyCommandSnapshot = {
  overview: {
    activeTrophies: number;
    vacantTrophies: number;
    guardianHeldTrophies: number;
    appOnlyTrophies: number;
    chainBackedTrophies: number;
    mintedNfts: number;
    pendingChallenges: number;
    pendingPayouts: number;
    failedPayouts: number;
    failedChainEvents: number;
    totalDailyTribute: number;
    totalDailyBountyGrowth: number;
    estimatedYearlyExposure: number;
    trophyRewardsWalletStatus: string;
    trophyRewardsWalletDetail: string;
    trophyRewardsWalletAddress: string | null;
    trophyRewardsWalletBalanceWolo: number | null;
    trophyRewardsWalletChainId: string | null;
    trophyTributeDueNow: number;
    trophyTributePaidToday: number;
    trophyTributeFailed: number;
    trophyTributeLastTxHash: string | null;
    trophyTributeLastPaidAt: string | null;
    trophyTributeLastRecipient: string | null;
    trophyTributeNextUtcDay: string;
    eligibilityConflicts: number;
  };
  trophies: TrophyRow[];
  challenges: TrophyChallengeRow[];
  payouts: TrophyPayoutRow[];
  events: TrophyEventRow[];
  settings: TrophySettingRow[];
  users: TrophyUserOption[];
  replays: Array<{
    id: number;
    label: string;
    winner: string | null;
    players: string[];
    playedOn: string | null;
  }>;
  generatedAt: string;
};

export type TrophyHolding = {
  id: string;
  type: string;
  kind: string;
  family: string;
  displayName: string;
  shortName: string;
  dailyWolo: number;
  bountyGrowthWolo: number;
  currentBountyWolo: number;
  routeHref: string;
  assetUrl: string;
  holderSince: string | null;
  status: string;
  chainStatus: string;
  nftId: string | null;
  eligibleNationality: string | null;
};
