CREATE TABLE IF NOT EXISTS "event_tiles" (
  "id" SERIAL PRIMARY KEY,
  "event_tile_id" VARCHAR(100) NOT NULL,
  "slug" VARCHAR(120) NOT NULL,
  "status" VARCHAR(24) NOT NULL DEFAULT 'draft',
  "priority" INTEGER NOT NULL DEFAULT 0,
  "is_published" BOOLEAN NOT NULL DEFAULT FALSE,
  "is_active" BOOLEAN NOT NULL DEFAULT FALSE,
  "name" VARCHAR(160) NOT NULL,
  "eyebrow" VARCHAR(160),
  "title" VARCHAR(180) NOT NULL,
  "subtitle" VARCHAR(220),
  "description" TEXT,
  "chapter_label" VARCHAR(160),
  "date_label" VARCHAR(160),
  "event_starts_at" TIMESTAMP(6),
  "event_ends_at" TIMESTAMP(6),
  "payout_badge_text" VARCHAR(120),
  "featured_badge_text" VARCHAR(120),
  "cta_label" VARCHAR(120),
  "cta_url" VARCHAR(500),
  "match_format" VARCHAR(120),
  "rules_summary" VARCHAR(255),
  "tournament_name" VARCHAR(180),
  "linked_trophy_id" INTEGER,
  "player_one_user_id" INTEGER,
  "player_one_name" VARCHAR(120),
  "player_one_avatar_url" VARCHAR(500),
  "player_two_user_id" INTEGER,
  "player_two_name" VARCHAR(120),
  "player_two_avatar_url" VARCHAR(500),
  "commissioner_user_id" INTEGER,
  "commissioner_name" VARCHAR(120),
  "commissioner_avatar_url" VARCHAR(500),
  "belt_image_url" VARCHAR(500),
  "background_image_url" VARCHAR(500),
  "mobile_background_image_url" VARCHAR(500),
  "gradient_from" VARCHAR(24) NOT NULL DEFAULT '#150704',
  "gradient_via" VARCHAR(24) NOT NULL DEFAULT '#05070d',
  "gradient_to" VARCHAR(24) NOT NULL DEFAULT '#071225',
  "overlay_opacity" DOUBLE PRECISION NOT NULL DEFAULT 0.24,
  "vignette_opacity" DOUBLE PRECISION NOT NULL DEFAULT 0.82,
  "theme" VARCHAR(40) NOT NULL DEFAULT 'royal',
  "created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "published_at" TIMESTAMP(6),
  CONSTRAINT "event_tiles_linked_trophy_fkey" FOREIGN KEY ("linked_trophy_id") REFERENCES "trophies"("id") ON DELETE SET NULL,
  CONSTRAINT "event_tiles_player_one_fkey" FOREIGN KEY ("player_one_user_id") REFERENCES "users"("id") ON DELETE SET NULL,
  CONSTRAINT "event_tiles_player_two_fkey" FOREIGN KEY ("player_two_user_id") REFERENCES "users"("id") ON DELETE SET NULL,
  CONSTRAINT "event_tiles_commissioner_fkey" FOREIGN KEY ("commissioner_user_id") REFERENCES "users"("id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "uq_event_tiles_event_tile_id" ON "event_tiles"("event_tile_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_event_tiles_slug" ON "event_tiles"("slug");
CREATE INDEX IF NOT EXISTS "ix_event_tiles_published_active_priority" ON "event_tiles"("is_published", "is_active", "priority");
CREATE INDEX IF NOT EXISTS "ix_event_tiles_status_updated" ON "event_tiles"("status", "updated_at");
CREATE INDEX IF NOT EXISTS "ix_event_tiles_linked_trophy" ON "event_tiles"("linked_trophy_id");
CREATE INDEX IF NOT EXISTS "ix_event_tiles_player_one" ON "event_tiles"("player_one_user_id");
CREATE INDEX IF NOT EXISTS "ix_event_tiles_player_two" ON "event_tiles"("player_two_user_id");
CREATE INDEX IF NOT EXISTS "ix_event_tiles_commissioner" ON "event_tiles"("commissioner_user_id");

INSERT INTO "event_tiles" (
  "event_tile_id",
  "slug",
  "status",
  "priority",
  "is_published",
  "is_active",
  "name",
  "eyebrow",
  "title",
  "subtitle",
  "description",
  "chapter_label",
  "date_label",
  "event_starts_at",
  "payout_badge_text",
  "featured_badge_text",
  "cta_label",
  "cta_url",
  "match_format",
  "rules_summary",
  "tournament_name",
  "player_one_user_id",
  "player_one_name",
  "player_one_avatar_url",
  "player_two_user_id",
  "player_two_name",
  "player_two_avatar_url",
  "commissioner_user_id",
  "commissioner_name",
  "commissioner_avatar_url",
  "belt_image_url",
  "gradient_from",
  "gradient_via",
  "gradient_to",
  "overlay_opacity",
  "vignette_opacity",
  "theme",
  "published_at"
)
SELECT
  'wolomania-i',
  'wolomania',
  'scheduled',
  100,
  TRUE,
  TRUE,
  'Wolomania',
  'The World Championship Event',
  'WOLOMANIA',
  'I',
  'The first AoE2WAR world championship event.',
  'July 10 · First Chapter',
  'July 10, 2026',
  TIMESTAMP '2026-07-10 20:00:00',
  'On-chain payout',
  'Featured Event',
  'Enter Wolomania',
  '/wolomania',
  'Best of 7',
  '100,000 WOLO',
  'AoE2HD Founders Cup',
  (SELECT "id" FROM "users" WHERE LOWER(COALESCE("in_game_name", '')) = 'jim' OR LOWER(COALESCE("steam_persona_name", '')) = 'jim' ORDER BY "id" LIMIT 1),
  'Jim',
  '/uploads/managed-assets/wolomania/jim_warrior.png',
  (SELECT "id" FROM "users" WHERE LOWER(COALESCE("in_game_name", '')) IN ('julio', 'julio alvarez') OR LOWER(COALESCE("steam_persona_name", '')) IN ('julio', 'julio alvarez') ORDER BY "id" LIMIT 1),
  'Julio Alvarez',
  '/uploads/managed-assets/wolomania/julio_warrior.png',
  (SELECT "id" FROM "users" WHERE LOWER(COALESCE("in_game_name", '')) = 'emaren' OR LOWER(COALESCE("steam_persona_name", '')) = 'emaren' ORDER BY "id" LIMIT 1),
  'Emaren',
  '/uploads/managed-assets/wolomania/emaren_warrior_2.png',
  '/uploads/managed-assets/wolomania/aoe2war_champ.png',
  '#150704',
  '#05070d',
  '#071225',
  0.24,
  0.82,
  'royal',
  CURRENT_TIMESTAMP
WHERE NOT EXISTS (
  SELECT 1 FROM "event_tiles" WHERE "event_tile_id" = 'wolomania-i'
);
