// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

loadEnv({ path: ".env.local", override: false });
loadEnv();

function normalizePrismaCliDatabaseUrl(
  raw: string | undefined,
): string | undefined {
  if (!raw) {
    return raw;
  }

  return raw.replace(
    /^postgresql\+asyncpg:\/\//,
    "postgresql://",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: normalizePrismaCliDatabaseUrl(process.env["DATABASE_URL"]),
  },
});
