import test from "node:test";
import assert from "node:assert/strict";
import { championshipClock,championshipCountdownSeconds,projectChampionshipChallenge,validateChampionshipBattleStart,validateChampionshipBattleFinal,championshipDefaultDecision,type ChampionshipParticipantProof } from "../lib/challengeChampionshipProtocol.ts";
const CREATED=new Date("2026-09-30T00:00:00Z"),clock=championshipClock(CREATED);
function participants(size=1):ChampionshipParticipantProof[]{return Array.from({length:size*2},(_,i)=>({userId:i+1,uid:`warrior${i}`,name:`Warrior ${i}`,side:i<size?"challenger":"defender",seat:i%size,steamId:`7656119800000000${i}`,accepted:true,funded:true,notified:true,fundingChallengeId:Math.floor(i%size)+1,fundingSide:i<size?"left":"right"}));}
function input(size=1){const p=participants(size);return{createdAt:CREATED,...clock,mode:"rm",teamSize:size,participants:p,battle:{id:1,sessionKey:"platform:123",startedAt:"2026-09-30T23:59:59Z",mode:"rm",state:"live" as "live"|"completed",startProvenance:"authenticated_live_observation" as const,startWatcherParticipantUids:p.filter(p=>p.side==="defender").map(p=>p.uid),watcherParticipantUids:p.map(p=>p.uid),players:p.map(p=>({steamId:p.steamId,teamId:p.side==="challenger"?"0":"1",winner:p.side==="challenger"}))}};}
function state(size=1){return{state:"open",...clock,defenseStartedAt:null,commissionerActionAt:null,titleName:"Championship",reasonCode:null,participants:participants(size)}};
test("server creation seals exactly 24h and Commissioner Hour 25",()=>{assert.equal(clock.challengeDeadline.toISOString(),"2026-10-01T00:00:00.000Z");assert.equal(clock.commissionerGraceDeadline.toISOString(),"2026-10-01T01:00:00.000Z");});
test("client seconds use server anchor and elapsed, with no local wall clock",()=>{assert.equal(championshipCountdownSeconds(clock.challengeDeadline.toISOString(),"2026-09-30T23:59:00Z",1000),59);assert.equal(championshipCountdownSeconds(clock.challengeDeadline.toISOString(),"2026-10-01T00:01:00Z"),0)});
test("acceptance and funding projections retain the original deadline",()=>{for(const funded of [false,true]){const s=state();s.participants[1]!.funded=funded;const projection=projectChampionshipChallenge(s,new Date("2026-09-30T23:00:00Z"),2);assert.equal(projection.challengeDeadline,clock.challengeDeadline.toISOString());assert.equal(projection.participants[1]!.canFund,!funded);}});
test("timely complete signed defending roster evidence freezes default",()=>{assert.equal(validateChampionshipBattleStart(input()).ok,true);assert.equal(championshipDefaultDecision({...state(),defenseStartedAt:new Date("2026-09-30T23:59:59Z")},new Date("2026-10-02T00:00:00Z")),"hold");});
test("a start exactly at Hour 24 does not qualify",()=>{const i=input();i.battle.startedAt=clock.challengeDeadline.toISOString();assert.deepEqual(validateChampionshipBattleStart(i),{ok:false,code:"MATCH_NOT_STARTED_BEFORE_DEADLINE"});});
test("a five-hour final remains valid after a timely start",()=>{const i=input();i.battle.state="completed";assert.equal(validateChampionshipBattleFinal(i).ok,true);assert.equal(projectChampionshipChallenge({...state(),state:"defense_in_progress",defenseStartedAt:new Date(i.battle.startedAt)},new Date("2026-10-01T05:00:00Z")).phase,"defense_in_progress");});
for(const size of [2,3,4])test(`${size}v${size} verifies exact team identities including team 0`,()=>{const i=input(size);assert.equal(validateChampionshipBattleStart(i).ok,true);i.battle.state="completed";assert.deepEqual(validateChampionshipBattleFinal(i),{ok:true,startedAt:new Date(i.battle.startedAt),winnerSide:"challenger"});});
test("a partly overlapping or substituted team cannot stop the timer",()=>{const i=input(2);i.battle.players[0]!.steamId="76561198099999999";assert.deepEqual(validateChampionshipBattleStart(i),{ok:false,code:"TEAM_ROSTER_MISMATCH"})});
test("RM evidence cannot defend a DM title",()=>{const i=input(2);i.mode="dm";assert.deepEqual(validateChampionshipBattleStart(i),{ok:false,code:"MODE_MISMATCH"})});
test("wrong size and inferred/crossed teams fail closed",()=>{const i=input(3);i.battle.players.pop();assert.equal(validateChampionshipBattleStart(i).ok,false);const crossed=input(2);crossed.battle.players[0]!.teamId="1";assert.equal(validateChampionshipBattleStart(crossed).ok,false)});
test("one credible defending signed observation preserves start but cannot award final",()=>{const i=input(2);i.battle.watcherParticipantUids=[i.participants[2]!.uid];i.battle.startWatcherParticipantUids=[i.participants[2]!.uid];assert.equal(validateChampionshipBattleStart(i).ok,true);i.battle.state="completed";assert.deepEqual(validateChampionshipBattleFinal(i),{ok:false,code:"FULL_ROSTER_PROOF_REQUIRED"})});
test("desync, incomplete winners and non-final proof cannot award title",()=>{const i=input();i.battle.state="completed";assert.equal(validateChampionshipBattleFinal({...i,battle:{...i.battle,desync:true}}).ok,false);i.battle.players[0]!.winner=false;assert.equal(validateChampionshipBattleFinal(i).ok,false);assert.equal(validateChampionshipBattleFinal({...input(),battle:{...input().battle,state:"completed",finalProofPending:true}}).ok,false)});
test("Hour 24 begins fixed grace; Hour 25 requires a valid claimant",()=>{const s=state();s.participants[1]!.funded=false;assert.equal(championshipDefaultDecision(s,clock.challengeDeadline),"grace");assert.equal(championshipDefaultDecision(s,clock.commissionerGraceDeadline),"eligible_default");s.participants[0]!.funded=false;assert.equal(championshipDefaultDecision(s,clock.commissionerGraceDeadline),"invalid_claimant")});
test("both ready without game start, missing delivery, or Commissioner action cannot manufacture default fault",()=>{assert.equal(championshipDefaultDecision(state(2),clock.commissionerGraceDeadline),"review");const s=state();s.participants[1]!.notified=false;assert.equal(championshipDefaultDecision(s,clock.commissionerGraceDeadline),"review");assert.equal(championshipDefaultDecision({...s,commissionerActionAt:clock.challengeDeadline},clock.commissionerGraceDeadline),"hold")});

test("an unsigned or parsed start timestamp cannot suppress default",()=>{const i=input();assert.deepEqual(validateChampionshipBattleStart({...i,battle:{...i.battle,startProvenance:undefined}}),{ok:false,code:"WATCHER_PROOF_MISSING"});assert.deepEqual(validateChampionshipBattleStart({...i,battle:{...i.battle,startWatcherParticipantUids:[i.participants[0]!.uid]}}),{ok:false,code:"WATCHER_PROOF_MISSING"});});
