export type KingdomChronicle = {
  id: string;
  label: string;
  title: string;
  body: string;
  dateLabel: string;
  kind: "chronicle" | "bounty" | "transaction" | "locked";
  amountWolo?: number;
  actor?: string;
  questActor?: string;
  avatarActor?: string;
  avatarActors?: string[];
  txHash?: string | null;
  href?: string | null;
  status?: string;
};

export const kingdomStats = [
  { label: "Current Age", value: "Feudal Age" },
  { label: "Chronicles", value: "22" },
  { label: "Bounties", value: "40" },
  { label: "Kingdom Wealth", value: "100,000,000 WOLO" },
  { label: "Watchers Active", value: "3" },
  { label: "Citizens", value: "18" },
  { label: "Joined The Quest", value: "18" },
];

const CHRONICLE_ROMAN_NUMERALS = [
  "I",
  "II",
  "III",
  "IV",
  "V",
  "VI",
  "VII",
  "VIII",
  "IX",
  "X",
  "XI",
  "XII",
  "XIII",
  "XIV",
  "XV",
  "XVI",
  "XVII",
  "XVIII",
  "XIX",
  "XX",
  "XXI",
  "XXII",
  "XXIII",
  "XXIV",
  "XXV",
  "XXVI",
  "XXVII",
  "XXVIII",
  "XXIX",
  "XXX",
] as const;

const rawKingdomChronicles: KingdomChronicle[] = [
  {
    id: "lone-fire",
    label: "Chronicle",
    title: "A Wolo from the Fire",
    body: "One man kept HD alive and bound it to WOLO. Before tribe, clan, or crown, there was only Emaren and the fire.",
    dateLabel: "Mar 23, 2026",
    kind: "chronicle",
    actor: "Emaren",
    questActor: "Emaren",
    avatarActor: "Emaren",
    status: "Founding fire",
  },
  {
    id: "pigman-sees-fire",
    label: "Chronicle",
    title: "A Shadow at the Fire",
    body: "[BDB]Pigman found the smoke and looked in, but did not yet speak. The first watcher at the edge of camp.",
    dateLabel: "Mar 26, 2026",
    kind: "chronicle",
    actor: "[BDB]Pigman",
    questActor: "[BDB]Pigman",
    avatarActor: "[BDB]Pigman",
    status: "Seen, no contact",
  },
  {
    id: "first-scout-answers",
    label: "Chronicle",
    title: "The First Scout Answers",
    body: "Julio came through the dark with hello there. The first real voice joined the fire.",
    dateLabel: "Mar 27, 2026",
    kind: "chronicle",
    actor: "Julio Alvarez",
    questActor: "Julio",
    avatarActor: "Julio Alvarez",
    status: "First contact",
  },
  {
    id: "deltaforce-joins-quest",
    label: "Chronicle",
    title: "The Quiet Sign-In",
    body: "Deltaforce signed in on the day the first scout answered. No contact yet, but the name entered the fire.",
    dateLabel: "Mar 27, 2026",
    kind: "chronicle",
    actor: "Deltaforce",
    questActor: "Deltaforce",
    avatarActor: "Deltaforce",
    status: "Signed in, no contact",
  },
  {
    id: "champion-appears",
    label: "Chronicle",
    title: "The Champion Appears",
    body: "Sniper arrived with yo. The field had a king before the Kingdom had walls.",
    dateLabel: "Apr 5, 2026",
    kind: "chronicle",
    actor: "Sniper",
    questActor: "Sniper",
    avatarActor: "Sniper",
    status: "Champion contact",
  },
  {
    id: "third-banner",
    label: "Chronicle",
    title: "The Third Banner",
    body: "[BDB]Pigman answers. The shadow at the fire became a banner in the camp.",
    dateLabel: "Apr 10, 2026",
    kind: "chronicle",
    actor: "[BDB]Pigman",
    avatarActor: "[BDB]Pigman",
    status: "Third contact",
  },
  {
    id: "guardian-checks-in",
    label: "Chronicle",
    title: "The Guardian Checks In",
    body: "Jim reached camp late and checked in by morning. The warband gained its guardian.",
    dateLabel: "Apr 24, 2026",
    kind: "chronicle",
    actor: "Jim",
    questActor: "Jim",
    avatarActor: "Jim",
    status: "Made contact",
  },
  {
    id: "silent-seat",
    label: "Chronicle",
    title: "The Silent Seat",
    body: "Dil_Pascana appeared before the eastern call, but never spoke. Presence is not contact.",
    dateLabel: "Apr 26, 2026",
    kind: "chronicle",
    actor: "Dil_Pascana",
    questActor: "Dil_Pascana",
    avatarActor: "Dil_Pascana",
    status: "No contact yet",
  },
  {
    id: "eastern-beacon",
    label: "Chronicle",
    title: "The Eastern Beacon",
    body: "- Ra 𓁛𓇳 crossed the line with hey Emaren. The fire was no longer local.",
    dateLabel: "Apr 26, 2026",
    kind: "chronicle",
    actor: "- Ra 𓁛𓇳",
    questActor: "- Ra 𓁛𓇳",
    avatarActor: "- Ra 𓁛𓇳",
    status: "Made contact",
  },
  {
    id: "champion-rises",
    label: "Chronicle",
    title: "The Champion Rises",
    body: "Sniper reached rank #1. The warband had its first crowned terror.",
    dateLabel: "May 23, 2026",
    kind: "chronicle",
    actor: "Sniper",
    avatarActor: "Sniper",
    status: "Leaderboard Rank #1",
  },
  {
    id: "first-coin",
    label: "Chronicle",
    title: "The First Coin",
    body: "Jim, Sniper, and Julio received mainnet WOLO. The promise became ledger.",
    dateLabel: "May 25 - Jun 5, 2026",
    kind: "transaction",
    amountWolo: 3000,
    actor: "Jim / Sniper / Julio",
    status: "First mainnet rewards",
  },
  {
    id: "bounty-first-scout",
    label: "Bounty #1",
    title: "The First Scout",
    body: "First Mainnet Watcher. Every kingdom needs its first scout.",
    dateLabel: "Jun 6, 2026",
    kind: "bounty",
    amountWolo: 125000,
    actor: "Julio Alvarez",
    avatarActor: "Julio Alvarez",
    status: "Completed",
  },
  {
    id: "bounty-first-guardian",
    label: "Bounty #2",
    title: "The First Guardian",
    body: "First Mainnet Staker. Every kingdom needs its first guardian.",
    dateLabel: "Jun 7, 2026",
    kind: "bounty",
    amountWolo: 10000,
    actor: "Jim",
    avatarActor: "Jim",
    status: "Completed",
  },
  {
    id: "signup-promise-kept",
    label: "Signup Bonus",
    title: "Signup Bonus.",
    body: "Jim came on the right day.",
    dateLabel: "Jun 7, 2026",
    kind: "transaction",
    amountWolo: 100000,
    actor: "Jim",
    avatarActor: "Jim",
    status: "Completed",
  },
  {
    id: "sladk0eshka-contact",
    label: "Chronicle",
    title: "The Valoper's Call",
    body: "Sladk0Eshka signed in and made contact. A new line opened from Valopers to the Kingdom.",
    dateLabel: "Jun 8, 2026",
    kind: "chronicle",
    actor: "Sladk0Eshka",
    questActor: "Sladk0Eshka",
    avatarActor: "Sladk0Eshka",
    status: "Made contact",
  },
  {
    id: "american-champion-shows-up",
    label: "Chronicle",
    title: "The American Champion",
    body: "Thirteen arrived. The USA Champion stepped out of the line and into the war.",
    dateLabel: "Jun 27, 2026",
    kind: "chronicle",
    actor: "Jim",
    avatarActor: "Jim",
    status: "Champion proof",
  },
  {
    id: "zodiac-first-contact",
    label: "Chronicle",
    title: "The Chaos Champion",
    body: "Zodiac made contact. A new voice entered the camp, and counsel came to the fire.",
    dateLabel: "Jun 27, 2026",
    kind: "chronicle",
    actor: "Zodiac",
    questActor: "Zodiac",
    avatarActor: "Zodiac",
    status: "First contact",
    href: "/zodiac",
  },
  {
    id: "no-pause-button",
    label: "Chronicle",
    title: "The Wolo Chronicles",
    body: "The first royal dispatch was written. The Kingdom learned to remember itself.",
    dateLabel: "Jul 1, 2026",
    kind: "chronicle",
    actor: "War Room Scribe",
    status: "Royal dispatch",
  },
  {
    id: "first-canceled-war",
    label: "Chronicle",
    title: "The War Not Fought",
    body: "A challenge was canceled cleanly. Not every war is fought; every war is recorded.",
    dateLabel: "Jul 2, 2026",
    kind: "chronicle",
    actor: "Emaren vs Jim",
    status: "Game canceled",
  },
  {
    id: "clan-chooses-zodiac",
    label: "Chronicle",
    title: "The Clan Chooses Zodiac",
    body: "Zodiac was named leader of the clan. The camp began forming offices.",
    dateLabel: "Jul 4, 2026",
    kind: "chronicle",
    actor: "Zodiac",
    status: "Clan office",
    avatarActor: "Zodiac",
    href: "/zodiac",
  },
  {
    id: "scribe-enters",
    label: "Chronicle",
    title: "The Scribe Enters",
    body: "The AI Scribe and Grimer entered the command room. Memory gained a voice.",
    dateLabel: "Jul 7, 2026",
    kind: "chronicle",
    actor: "The AI Scribe / Grimer",
    avatarActors: ["The AI Scribe", "Grimer"],
    status: "Command room",
  },
  {
    id: "first-spectator-bet-2026-07-07",
    label: "Chronicle",
    dateLabel: "Jul 7, 2026",
    title: "First Spectator Bet",
    body: "Jim put 100 WOLO on the field against Emaren and lost.",
    kind: "transaction",
    actor: "Jim / Emaren",
    amountWolo: 100,
    status: "Jim lost",
    href: "/staking",
  },
  {
    id: "bounty-batch-uploader-live",
    label: "Bounty #39",
    title: "Batch Uploader is Live",
    body: "1M WOLO to Jim. Old war files now upload and parse at the click of a button. This is not a game. This is War.",
    dateLabel: "Jul 8, 2026",
    kind: "bounty",
    amountWolo: 1000000,
    actor: "Jim",
    avatarActor: "Jim",
    status: "Completed",
  },
  {
    id: "bounty-old-war-stories",
    label: "Bounty #40",
    title: "Jim's Old War Stories",
    body: "1M WOLO to Jim for bringing the old wars back to the fire. 1,993 other ways to die.",
    dateLabel: "Jul 8, 2026",
    kind: "bounty",
    amountWolo: 1000000,
    actor: "Jim",
    avatarActor: "Jim",
    status: "Completed",
  },
  {
    id: "three-in-a-day-2026-07-12",
    label: "Chronicle",
    title: "Three in a Day",
    body: "Maxi, Tekki, and BeTiKo sign up for war.",
    dateLabel: "Jul 12, 2026",
    kind: "chronicle",
    actor: "Maxi / Tekki / BeTiKo",
    questActor: "Maxi, Tekki, and BeTiKo",
    avatarActors: ["Maxi", "Tekki", "BeTiKo"],
    status: "Three warriors enter",
  },
  {
    id: "legend-sultan-enters-2026-07-16",
    label: "Chronicle",
    title: "A Legendary Hall",
    body: "LeGenD_Sultan walks into the kingdom, requesting a legendary hall of his own. The kingdom is only too happy to provide.",
    dateLabel: "Jul 16, 2026",
    kind: "chronicle",
    actor: "LeGenD_Sultan",
    questActor: "LeGenD_Sultan",
    avatarActor: "LeGenD_Sultan",
    status: "Legendary hall requested",
  },
  {
    id: "scavanger-ab-scouts-2026-07-19",
    label: "Chronicle",
    title: "Scouting the Kingdom",
    body: "Scavanger_Ab scouts out the kingdom for himself.",
    dateLabel: "Jul 19, 2026",
    kind: "chronicle",
    actor: "Scavanger_Ab",
    questActor: "Scavanger_Ab",
    avatarActor: "Scavanger_Ab",
    status: "Kingdom scouted",
  },
  {
    id: "champion-answers",
    label: "Chronicle",
    title: "The Champion Answers",
    body: "Sniper runs the watcher. The king takes the field.",
    dateLabel: "Locked",
    kind: "locked",
    actor: "Sniper",
    avatarActor: "Sniper",
  },
  {
    id: "zodiac-watcher-locked",
    label: "Chronicle",
    title: "Zodiac Runs the Watcher",
    body: "Zodiac runs the watcher and proof reaches the fire.",
    dateLabel: "Locked",
    kind: "locked",
    actor: "Zodiac",
    avatarActor: "Zodiac",
  },
  {
    id: "second-watchtower",
    label: "Chronicle",
    title: "The Fourth Watcher",
    body: "A fourth watcher rises. The Kingdom sees further.",
    dateLabel: "Locked",
    kind: "locked",
  },
  {
    id: "first-wager",
    label: "Chronicle",
    title: "The First Wager",
    body: "The first true community wager is made.",
    dateLabel: "Locked",
    kind: "locked",
  },
  {
    id: "first-festival",
    label: "Chronicle",
    title: "The First Festival",
    body: "Wolomania gathers the realm.",
    dateLabel: "Locked",
    kind: "locked",
  },
  {
    id: "castle-age",
    label: "Age Gate",
    title: "Castle Age",
    body: "Stone walls. Royal houses. Crown law.",
    dateLabel: "Locked",
    kind: "locked",
  },
  {
    id: "imperial-age",
    label: "Age Gate",
    title: "Imperial Age",
    body: "The empire rises from proof.",
    dateLabel: "Locked",
    kind: "locked",
  },
];

let kingdomChronicleNumber = 0;

export const kingdomChronicles: KingdomChronicle[] = rawKingdomChronicles.map((item) => {
  if (item.label !== "Chronicle") return item;

  const roman = CHRONICLE_ROMAN_NUMERALS[kingdomChronicleNumber] ?? String(kingdomChronicleNumber + 1);
  kingdomChronicleNumber += 1;

  return {
    ...item,
    label: `Chronicle ${roman}`,
  };
});



export const forumChannels = [
  { label: "Champion Corner", count: 3 },
  { label: "Official Announcements", count: 12 },
  { label: "Bounty Board", count: 9 },
  { label: "Tournaments", count: 6 },
  { label: "Strategy & Build Orders", count: 24 },
  { label: "Maps & Civs", count: 18 },
  { label: "New Players", count: 17 },
  { label: "Watcher Help", count: 11 },
  { label: "Bug Reports", count: 7 },
  { label: "Suggestions", count: 10 },
  { label: "Introduce Yourself", count: 14 },
  { label: "Off-Topic Tavern", count: 20 },
];

export const featuredForumThreads = [
  {
    title: "April Champion Breakdown: Macro, Map Control & Mind Games",
    author: "Sniper",
    tag: "Champion Post",
    replies: 128,
    views: "2.4K",
    hot: true,
  },
  {
    title: "World Championship Open Challenge - Who Steps Up?",
    author: "AoE2WAR Official",
    tag: "Bounty Board",
    replies: 73,
    views: "1.8K",
  },
  {
    title: "New Belt: Chaos Champion - How It Works",
    author: "AoE2WAR Official",
    tag: "Announcement",
    replies: 89,
    views: "2.9K",
  },
  {
    title: "Which Civ is MOST FUN to watch right now?",
    author: "MangudaiMaster",
    tag: "Hot Discussion",
    replies: 96,
    views: "1.6K",
    hot: true,
  },
];

export const recentForumPosts = [
  "Why early aggression still works in 2026",
  "Casted Game: Sniper vs. DauT - Epic Arena Match",
  "How does matchmaking ELO actually work?",
  "2v2 Arabia is pure chaos and I love it",
  "DE vs HD - What's the better experience?",
  "My full castle drop build, step by step",
  "AoE2WAR Stats API - Now open for devs",
  "Share your craziest comeback wins",
];
