export type ChallengeSettlementLedgerRow = {
  status: string;
  amountWolo: number;
  txHash?: string | null;
};

export type ChallengeFinancialConservationInput = {
  fundingEachWolo: number;
  leftFunded: boolean;
  rightFunded: boolean;

  /*
   * Historical settlement ledger, not merely transfers
   * generated by the current planner.
   */
  settlements: readonly ChallengeSettlementLedgerRow[];

  /*
   * Value the current plan still intends to execute.
   * Already-executed transfers must not be included.
   */
  pendingPlanWolo?: number;
};

export type ChallengeFinancialConservation = {
  ok: boolean;

  fundedParticipantCount: number;
  fundedLiabilityWolo: number;

  historicalExecutedWolo: number;
  pendingPlanWolo: number;
  projectedSettlementWolo: number;

  remainingLiabilityWolo: number;

  overSettledWolo: number;
  projectedOverageWolo: number;

  blockers: string[];
};

function normalizeStatus(
  value: string | null | undefined,
) {
  return (value || "")
    .trim()
    .toLowerCase();
}

function validWoloAmount(
  value: number,
) {
  return (
    Number.isSafeInteger(value) &&
    value >= 0
  );
}

/*
 * Superseded rows are historical planning evidence.
 *
 * They are NOT an outstanding economic obligation and
 * therefore must never inflate pending/refund projections.
 */
export function isEffectiveChallengeSettlement(
  settlement: Pick<
    ChallengeSettlementLedgerRow,
    "status"
  >,
) {
  return (
    normalizeStatus(
      settlement.status,
    ) !== "superseded"
  );
}

export function effectiveChallengeSettlementRows<
  T extends Pick<
    ChallengeSettlementLedgerRow,
    "status"
  >,
>(
  settlements: readonly T[],
) {
  return settlements.filter(
    isEffectiveChallengeSettlement,
  );
}

/*
 * "Executed" is intentionally fail-closed here.
 *
 * If the application ledger says a transfer executed,
 * its amount consumes Challenge liability even if its
 * tx hash later proves unavailable.
 *
 * We never regain spending authority merely because
 * external proof has gone missing.
 */
export function historicalChallengeSettlementExecutedWolo(
  settlements: readonly ChallengeSettlementLedgerRow[],
) {
  let total = 0;

  for (const settlement of settlements) {
    if (
      normalizeStatus(
        settlement.status,
      ) !== "executed"
    ) {
      continue;
    }

    if (
      !validWoloAmount(
        settlement.amountWolo,
      )
    ) {
      continue;
    }

    total +=
      settlement.amountWolo;
  }

  return total;
}

export function deriveChallengeFinancialConservation(
  input: ChallengeFinancialConservationInput,
): ChallengeFinancialConservation {
  const blockers: string[] = [];

  if (
    !validWoloAmount(
      input.fundingEachWolo,
    )
  ) {
    blockers.push(
      "Challenge funding terms are not a valid non-negative integer WOLO amount.",
    );
  }

  const fundingEachWolo =
    validWoloAmount(
      input.fundingEachWolo,
    )
      ? input.fundingEachWolo
      : 0;

  const fundedParticipantCount =
    Number(input.leftFunded) +
    Number(input.rightFunded);

  const fundedLiabilityWolo =
    fundedParticipantCount *
    fundingEachWolo;

  let historicalExecutedWolo = 0;

  for (const settlement of input.settlements) {
    if (
      normalizeStatus(
        settlement.status,
      ) !== "executed"
    ) {
      continue;
    }

    if (
      !validWoloAmount(
        settlement.amountWolo,
      )
    ) {
      blockers.push(
        "Executed Challenge settlement contains an invalid WOLO amount.",
      );
      continue;
    }

    historicalExecutedWolo +=
      settlement.amountWolo;
  }

  const pendingPlanWolo =
    validWoloAmount(
      input.pendingPlanWolo ?? 0,
    )
      ? input.pendingPlanWolo ?? 0
      : 0;

  if (
    !validWoloAmount(
      input.pendingPlanWolo ?? 0,
    )
  ) {
    blockers.push(
      "Challenge settlement plan contains an invalid pending WOLO amount.",
    );
  }

  const projectedSettlementWolo =
    historicalExecutedWolo +
    pendingPlanWolo;

  const remainingLiabilityWolo =
    Math.max(
      0,
      fundedLiabilityWolo -
        historicalExecutedWolo,
    );

  const overSettledWolo =
    Math.max(
      0,
      historicalExecutedWolo -
        fundedLiabilityWolo,
    );

  const projectedOverageWolo =
    Math.max(
      0,
      projectedSettlementWolo -
        fundedLiabilityWolo,
    );

  if (
    overSettledWolo > 0
  ) {
    blockers.unshift(
      `FINANCIAL CONSERVATION BREACH: ` +
      `Challenge ledger already records ` +
      `${historicalExecutedWolo.toLocaleString()} WOLO executed ` +
      `against ${fundedLiabilityWolo.toLocaleString()} WOLO ` +
      `of funded principal. Further settlement is forbidden.`,
    );
  } else if (
    projectedOverageWolo > 0
  ) {
    blockers.unshift(
      `FINANCIAL CONSERVATION BLOCK: ` +
      `executed settlement plus this plan would reach ` +
      `${projectedSettlementWolo.toLocaleString()} WOLO ` +
      `against ${fundedLiabilityWolo.toLocaleString()} WOLO ` +
      `of funded principal.`,
    );
  }

  return {
    ok: blockers.length === 0,

    fundedParticipantCount,
    fundedLiabilityWolo,

    historicalExecutedWolo,
    pendingPlanWolo,
    projectedSettlementWolo,

    remainingLiabilityWolo,

    overSettledWolo,
    projectedOverageWolo,

    blockers,
  };
}
