// GENERATED by scripts/generate_page_change_manifest.py
// Do not hand-edit. Versions change only when page-specific source changes.

export const PAGE_CHANGE_MANIFEST = [
  {
    href: "/kingdom",
    label: "Kingdom",
    version: "src-e1475a39cedebdb70634",
  },
  {
    href: "/oracle",
    label: "The Oracle",
    version: "src-7ffd15040a57dea8e395",
  },
  {
    href: "/leaderboard",
    label: "Leaderboard",
    version: "src-92adf8e684a9a7c49785",
  },
  {
    href: "/champions",
    label: "Champions",
    version: "src-0638ad702787b0f34bab",
  },
  {
    href: "/chaosium",
    label: "Chaosium",
    version: "src-ef580d73f9c9eb47d0b7",
  },
  {
    href: "/olympia",
    label: "Olympia",
    version: "src-3d42dc8473a3bb8da486",
  },
  {
    href: "/leagues",
    label: "Leagues",
    version: "src-2c6e4bfe4512b5809255",
  },
  {
    href: "/national-champions",
    label: "Nations",
    version: "src-eccd52b4dedf36a15699",
  },
  {
    href: "/clans",
    label: "Clans",
    version: "src-8c7fc5296e31e43f7bb5",
  },
  {
    href: "/academy",
    label: "Academy",
    version: "src-5b6ee7e99e39ab934ea4",
  },
  {
    href: "/market",
    label: "Marketplace",
    version: "src-13e9bc367c50f400312c",
  },
  {
    href: "/ai",
    label: "AI Council",
    version: "src-873ba2ffcdfcb844bc93",
  },
  {
    href: "/bounties",
    label: "Bounties",
    version: "src-bfc43ba099d945b2049d",
  },
  {
    href: "/forum",
    label: "Forum",
    version: "src-a1774b3ae767492c332c",
  },
  {
    href: "/radio",
    label: "Radio WOLO",
    version: "src-6a58574bcf23a6541015",
  },
  {
    href: "/workshop",
    label: "The Workshop",
    version: "src-a8400e0d5808be3e1018",
  },
  {
    href: "/kingdom-intelligence",
    label: "Kingdom Intelligence",
    version: "src-2b425b7ed9c1d7b840ea",
  },
  {
    href: "/game-stats",
    label: "Parser Observatory",
    version: "src-9f9fac96dab226d8a3a0",
  },
  {
    href: "/traffic",
    label: "Traffic Observatory",
    version: "src-9c1303ce9b4b7f824452",
  },
  {
    href: "/kingdom-forge",
    label: "Kingdom Forge",
    version: "src-f8a9c0109baff44699c7",
  },
  {
    href: "/round-chamber",
    label: "The Chamber",
    version: "src-95a089ff68c2d996c2d5",
  },
  {
    href: "/statistics",
    label: "Kingdom Statistics",
    version: "src-c2058abd4b0543a475a9",
  },
  {
    href: "/speed",
    label: "Speed",
    version: "src-75f0d3084c8236e92b55",
  },
] as const;
