// GENERATED by scripts/generate_page_change_manifest.py
// Do not hand-edit. Versions change only when page-specific source changes.

export const PAGE_CHANGE_MANIFEST = [
  {
    href: "/kingdom",
    label: "Kingdom",
    version: "src-315cad348f8bd0244ea9",
  },
  {
    href: "/oracle",
    label: "The Oracle",
    version: "src-7ffd15040a57dea8e395",
  },
  {
    href: "/leaderboard",
    label: "Leaderboard",
    version: "src-92adf8e684a9a7c49785",
  },
  {
    href: "/champions",
    label: "Champions",
    version: "src-c5808212a6a119138152",
  },
  {
    href: "/national-champions",
    label: "Nations",
    version: "src-eccd52b4dedf36a15699",
  },
  {
    href: "/clans",
    label: "Clans",
    version: "src-6ba9ccf343fb55c6afb0",
  },
  {
    href: "/academy",
    label: "Academy",
    version: "src-5b6ee7e99e39ab934ea4",
  },
  {
    href: "/market",
    label: "Marketplace",
    version: "src-13e9bc367c50f400312c",
  },
  {
    href: "/ai",
    label: "AI Council",
    version: "src-873ba2ffcdfcb844bc93",
  },
  {
    href: "/bounties",
    label: "Bounties",
    version: "src-9d8bf73102c746c92fa9",
  },
  {
    href: "/forum",
    label: "Forum",
    version: "src-a1774b3ae767492c332c",
  },
  {
    href: "/radio",
    label: "Radio WOLO",
    version: "src-70bff92716d0d92b7f3b",
  },
  {
    href: "/workshop",
    label: "The Workshop",
    version: "src-9818e7549ad59368454c",
  },
  {
    href: "/kingdom-intelligence",
    label: "Kingdom Intelligence",
    version: "src-2b425b7ed9c1d7b840ea",
  },
  {
    href: "/game-stats",
    label: "Parser Observatory",
    version: "src-1ac51bba50e0446d5576",
  },
  {
    href: "/traffic",
    label: "Traffic Observatory",
    version: "src-9c1303ce9b4b7f824452",
  },
  {
    href: "/kingdom-forge",
    label: "Kingdom Forge",
    version: "src-1f81de96a9d8751a0718",
  },
  {
    href: "/round-chamber",
    label: "The Chamber",
    version: "src-95a089ff68c2d996c2d5",
  },
  {
    href: "/statistics",
    label: "Kingdom Statistics",
    version: "src-c2058abd4b0543a475a9",
  },
  {
    href: "/speed",
    label: "Speed",
    version: "src-8d7fc535fffe86294cdf",
  },
] as const;
