// GENERATED by scripts/generate_page_change_manifest.py
// Do not hand-edit. Versions change only when page-specific source changes.

export const PAGE_CHANGE_MANIFEST = [
  {
    href: "/kingdom",
    label: "Kingdom",
    version: "src-192988f1d1ef468c60bf",
  },
  {
    href: "/oracle",
    label: "The Oracle",
    version: "src-5a941636c8ddd95aed89",
  },
  {
    href: "/leaderboard",
    label: "Leaderboard",
    version: "src-36b662b1e7de568fae1e",
  },
  {
    href: "/champions",
    label: "Champions",
    version: "src-f4f44d05bb6f3a4e4180",
  },
  {
    href: "/national-champions",
    label: "Nations",
    version: "src-902f6751950262c6d7df",
  },
  {
    href: "/clans",
    label: "Clans",
    version: "src-74dd15cdf194c5886601",
  },
  {
    href: "/academy",
    label: "Academy",
    version: "src-a1ca6772804b9f6d30e5",
  },
  {
    href: "/market",
    label: "Marketplace",
    version: "src-89591e15f56034d6f6f1",
  },
  {
    href: "/ai",
    label: "AI Council",
    version: "src-873ba2ffcdfcb844bc93",
  },
  {
    href: "/bounties",
    label: "Bounties",
    version: "src-b9b14e10edf5e17a9aa1",
  },
  {
    href: "/forum",
    label: "Forum",
    version: "src-a1774b3ae767492c332c",
  },
  {
    href: "/radio",
    label: "Radio WOLO",
    version: "src-aa92d5e6f572d39633b6",
  },
  {
    href: "/workshop",
    label: "The Workshop",
    version: "src-d4d74bbd9a6ff7121fb5",
  },
  {
    href: "/game-stats",
    label: "Parser Observatory",
    version: "src-d2962c222ebc012ea314",
  },
  {
    href: "/traffic",
    label: "Traffic Observatory",
    version: "src-b321bb617f094b3417d7",
  },
  {
    href: "/kingdom-forge",
    label: "Kingdom Forge",
    version: "src-1f81de96a9d8751a0718",
  },
  {
    href: "/round-chamber",
    label: "The Chamber",
    version: "src-95a089ff68c2d996c2d5",
  },
  {
    href: "/statistics",
    label: "Kingdom Statistics",
    version: "src-c2058abd4b0543a475a9",
  },
  {
    href: "/speed",
    label: "Speed",
    version: "src-b12768780716a2d4af89",
  },
] as const;
