"use client";

import { FormEvent, useState } from "react";
import { RADIO_RIGHTS_STATEMENT } from "@/lib/radioWolo";

export default function RadioSubmissionForm() {
  const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (pending) return; setPending(true); setError(null); setNotice(null); const form = event.currentTarget; const data = new FormData(form); try { const response = await fetch("/api/radio/submissions", { method: "POST", body: data }); const payload = (await response.json().catch(() => ({}))) as { detail?: string; submission?: { publicId: string } }; if (!response.ok) throw new Error(payload.detail || "Could not submit track."); setNotice(`Submission preserved. Reference ${payload.submission?.publicId || "created"}.`); form.reset(); } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "Could not submit track."); } finally { setPending(false); } }
  return <form onSubmit={(event) => void submit(event)} className="space-y-5 rounded-[1.8rem] border border-white/10 bg-slate-950/75 p-6 sm:p-8"><div className="grid gap-4 sm:grid-cols-2"><Field name="artistName" label="Artist name" maxLength={160} required /><Field name="trackTitle" label="Track title" maxLength={200} required /><Field name="genre" label="Genre / mood" maxLength={100} /><Field name="contactEmail" label="Contact email" type="email" maxLength={254} required /><Field name="contactDiscord" label="Discord · optional" maxLength={120} /><label className="space-y-2 text-sm text-slate-300"><span>Audio · MP3, WAV, OGG, M4A · 60 MB max</span><input name="audio" type="file" accept="audio/mpeg,audio/wav,audio/ogg,audio/mp4,.mp3,.wav,.ogg,.m4a" required className="block w-full rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-sm" /></label><label className="space-y-2 text-sm text-slate-300"><span>Artwork · optional · PNG, JPEG, WebP</span><input name="artwork" type="file" accept="image/png,image/jpeg,image/webp" className="block w-full rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-sm" /></label></div><label className="block space-y-2 text-sm text-slate-300"><span>Notes to Radio WOLO</span><textarea name="notes" rows={5} maxLength={6000} className="w-full rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-white outline-none focus:border-fuchsia-200/35" /></label><label className="flex items-start gap-3 rounded-2xl border border-amber-200/12 bg-amber-300/[0.05] p-4 text-sm leading-6 text-slate-300"><input name="rightsAccepted" value="true" type="checkbox" required className="mt-1" /><span>{RADIO_RIGHTS_STATEMENT}</span></label>{error ? <div className="rounded-xl border border-rose-300/20 bg-rose-500/10 p-4 text-rose-100">{error}</div> : null}{notice ? <div className="rounded-xl border border-emerald-300/20 bg-emerald-500/10 p-4 text-emerald-100">{notice}</div> : null}<button disabled={pending} className="rounded-full bg-fuchsia-200 px-6 py-3 text-sm font-bold text-slate-950 disabled:opacity-50">{pending ? "Preserving submission…" : "Submit to Radio WOLO"}</button></form>;
}
function Field({ name, label, type = "text", maxLength, required }: { name: string; label: string; type?: string; maxLength: number; required?: boolean }) { return <label className="space-y-2 text-sm text-slate-300"><span>{label}</span><input name={name} type={type} maxLength={maxLength} required={required} className="w-full rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-white outline-none focus:border-fuchsia-200/35" /></label>; }
