#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "lib/pageChangeManifest.generated.ts"

PAGES = [
    ("/kingdom", "Kingdom"),
    ("/oracle", "The Oracle"),
    ("/leaderboard", "Leaderboard"),
    ("/champions", "Champions"),
    ("/national-champions", "Nations"),
    ("/clans", "Clans"),
    ("/academy", "Academy"),
    ("/market", "Marketplace"),
    ("/ai", "AI Council"),
    ("/bounties", "Bounties"),
    ("/forum", "Forum"),
    ("/radio", "Radio WOLO"),
    ("/workshop", "The Workshop"),
    ("/kingdom-intelligence", "Kingdom Intelligence"),
    ("/game-stats", "Parser Observatory"),
    ("/traffic", "Traffic Observatory"),
    ("/kingdom-forge", "Kingdom Forge"),
    ("/round-chamber", "The Chamber"),
    ("/statistics", "Kingdom Statistics"),
    ("/speed", "Speed"),
]

EXTENSIONS = {".ts", ".tsx", ".js", ".jsx", ".json", ".css", ".md"}


def source_files(href: str) -> list[Path]:
    route = href.strip("/")
    candidates: list[Path] = []
    for directory in [ROOT / "app" / route, ROOT / "components" / route, ROOT / "lib" / route]:
        if directory.exists():
            candidates.extend(
                p for p in directory.rglob("*")
                if p.is_file() and p.suffix in EXTENSIONS
            )
    for direct in [ROOT / "lib" / f"{route}.ts", ROOT / "lib" / f"{route}.tsx"]:
        if direct.exists():
            candidates.append(direct)
    unique = sorted(set(candidates), key=lambda p: str(p.relative_to(ROOT)))
    if not unique:
        raise SystemExit(f"No page-specific source files found for {href}")
    return unique


def version_for(href: str) -> tuple[str, int]:
    digest = hashlib.sha256()
    files = source_files(href)
    for path in files:
        rel = str(path.relative_to(ROOT))
        digest.update(rel.encode("utf-8"))
        digest.update(b"\\0")
        digest.update(path.read_bytes())
        digest.update(b"\\0")
    return f"src-{digest.hexdigest()[:20]}", len(files)


rows = []
for href, label in PAGES:
    version, count = version_for(href)
    rows.append((href, label, version, count))

lines = [
    "// GENERATED by scripts/generate_page_change_manifest.py",
    "// Do not hand-edit. Versions change only when page-specific source changes.",
    "",
    "export const PAGE_CHANGE_MANIFEST = [",
]
for href, label, version, _count in rows:
    lines.extend([
        "  {",
        f"    href: {json.dumps(href)},",
        f"    label: {json.dumps(label)},",
        f"    version: {json.dumps(version)},",
        "  },",
    ])
lines.extend(["] as const;", ""])
OUT.write_text("\n".join(lines), encoding="utf-8")

print("PAGE CHANGE MANIFEST")
for href, label, version, count in rows:
    print(f"{href:22} {version}  {label}  ({count} source files)")
print(f"Wrote {OUT.relative_to(ROOT)}")
